### ISSUE TITLE
Support for iframe-video-area with a preview image first

### ISSUE THREAD

**Issue by melker** [orestbida/iframemanager#11]
What we want for video-iframes is this:

Editor set up an area that shall contain an embedded video and may also specify an (internal) preview-image.

Visitor sees initially: (both those that not has accepted and those who has accepted that category)
Preview-image and a play button on top of it.
If editor did not specify a preview-image a default is used.
(I.e. it only load data from us, never the external service)

When visitor presses image or play-button:

If visitor has accepted that service, the video with the iframe is displayed. (loading data from external service)

If visitor not (yet) has accepted it displays a text and buttons on top of the image (white-faded).  Just as iframemanager looks like when you not yet have accepted the service. 
"Accept this", and ( "Accept all of type X" or "Open cookie settings" ). The first one only loads the iframe of that vidoe and the second one calls cookieconsent to accept all of that type or open dialog.

NOTE: Currently I have set this up myself with cookieconsent, and are not (yet?) using iframemanager.

**Comment by melker** [comment]
What I think this boils down to is a feature request for a setting on categories to initially display only the preview image and another for the url of the image on top (the play button in this case). And handle the checking and displaying when someone clicks on it.

**Comment by orestbida** [comment]
Sorry, this won't be worked on as I don't like the idea; it forces the user to take an extra step.
