### ISSUE TITLE
Handle non-js-browsers, allow them to get to the external service as well.

### ISSUE THREAD

**Issue by melker** [orestbida/iframemanager#12]
Idea: Initially we could add a 
`<a href="urlOfExternalService" rel="noreferrer">SomeTitle</a>`
either as the thing to be replaced instead of the div or we can add it inside the div and the javascript will remove the link once triggered (it could have some data-cc-nonjs attribute or something.

**Comment by melker** [comment]
Hmmm... I realize that this maybe this already works if I add the link is inside the div. Then this issue is a request for it being mentioned in the documentation as an example of handling non-js-browsers I guess :-)

**Comment by orestbida** [comment]
Checkout the [docs.](https://github.com/orestbida/iframemanager#placeholder-for-non-js-browsers) for an example.
