### ISSUE TITLE
Turn off cookies

### ISSUE THREAD

**Issue by YonKuma** [orestbida/iframemanager#13]
I have a website that doesn't currently store any user data, and I'd like to use this plugin to require consent to load in embedded video. I'd rather not have to add a GDPR cookie disclosure just to save GDPR consent information, so is there a way to turn off cookies on this script and just require the user to consent every time they want to load in a video?

**Comment by orestbida** [comment]
Hi @YonKuma,

there is no option (yet) to do this but you can use css to hide the second button:

```css
div[data-service] .c-l-b{
    display: none!important;
}
```


When v1.1 comes out, both buttons will become optional.

**Comment by YonKuma** [comment]
Awesome, thanks!
