### ISSUE TITLE
Is it possible to combine iframemanager with cookieconsent?

### ISSUE THREAD

**Issue by wadid** [orestbida/iframemanager#16]
Is there a way to accept the iframes in the cookieconsent menu?

**Comment by orestbida** [comment]
Yes. you can use the [API](https://github.com/orestbida/iframemanager#apis)

**Comment by aspoet** [comment]
Is it possible to add `data-action` and` data-service` attributes to the iframemanager buttons?

This way a click on "don't ask again" would trigger the appropriate cookie category in CookieConsent as well.
