### ISSUE TITLE
Is it possible to read the accepted/rejected cookies from iframemanager and show them in cookieconsent?

### ISSUE THREAD

**Issue by tobkum** [orestbida/iframemanager#18]
I got it to work so I can accept a cookie category in cookieconsent and have it also accept/deny the appropriate ones for iframemanager. Is it possible the other way round? So someone rejects the "external" category in CC, but then clicks on "Don't ask again" on an embedded YT iframe. This will not show up in CCs settings, since I cannot read it the other way round - or did I miss something?
Cheers!

**Comment by aspoet** [comment]
Was wondering the same thing, I cannot work out a way to do that from the docs without altering the iframemanager.js script to create the button already with the `data-service` attached.

**Comment by orestbida** [comment]
This will be addressed in the upcoming `v1.2.0`. Closing this issue since it will be tracked in #22.
