### ISSUE TITLE
Example for leaflet map with open street map layer?

### ISSUE THREAD

**Issue by stefaneidelloth** [orestbida/iframemanager#19]
Could/should I use iframemanager to embed a leaflet map in a gdpr complient way? Is there some example? Or can you recommend a different solution? 

I would like to define the leaflet map and its layers on the same web page but defer the loading of background layers from external servers until a user explicitly confirms it. 

=> Instead of an embed url, can I also specify some html content (containing the map definition) directly?

Related: #9

**Comment by PixelBaer** [comment]
This would be a very welcome addition to this script. 
Have you found another reliable solution?

**Comment by stefaneidelloth** [comment]
I implemented my own solution. 
[gdpr--wrapper.zip](https://github.com/orestbida/iframemanager/files/9900571/gdpr--wrapper.zip)
