### ISSUE TITLE
How to iframe with arguments?

### ISSUE THREAD

**Issue by lamtonylam** [orestbida/iframemanager#2]
Hi, love the project!

However, can I add iframe arguments like width etc.?

For example, this one:

`<script src="https://static.airtable.com/js/embed/embed_snippet_v1.js"></script><iframe class="airtable-embed airtable-dynamic-height" src="https://airtable.com/embed/shr5EBHUmHzStubDx?backgroundColor=orange" frameborder="0" onmousewheel="" width="100%" height="1541" style="background: transparent; border: 1px solid #ccc;" loading="lazy"></iframe>
`

**Comment by orestbida** [comment]
Hi @lamtonylam,

as of now, this plugin is better suited for iframes containing videos. There is no proper support for custom “widgets”. Expect the upcoming v1.1 to improve on this aspect.

**Comment by lamtonylam** [comment]
Thank you for answering!

**Comment by n3t** [comment]
Additional attributes is trying to solve PR #17
