### ISSUE TITLE
Google maps embed marker not showing

### ISSUE THREAD

**Issue by tombroucke** [orestbida/iframemanager#24]
Hi,

I'm trying to get this to work with the normal embed iframe (not through the embed api) e.g. `<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d40299.30426384719!2d4.340397959224176!3d50.85511876045215!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c3a4ed73c76867%3A0xc18b3a66787302a7!2sBrussel!5e0!3m2!1snl!2sbe!4v1666528240497!5m2!1snl!2sbe" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`. When loading the iframe, the src string is encoded (`video.iframe.src = encodeURI(src);`), which prevents the marker from being rendered. When removing the encodeURI() function, the marker is render correctly.

Could you add a flag to disable the encoding?

Kind regards,
Tom

**Comment by alxndr-w** [comment]
Does https://github.com/orestbida/iframemanager/issues/9#issuecomment-1156573117 solve your problem?

**Comment by tombroucke** [comment]
Allright, thanks. I'm using PHP's urldecode() on the pb parameter, and setting this as the data-id on the div. Thanks!
