### ISSUE TITLE
iframemanager doesn't work

### ISSUE THREAD

**Issue by RedstonePfalz** [orestbida/iframemanager#33]
Hello,
I am trying to use the iframemanager together with the cookieconsent plugin. The cookieconsent works, but the iframemanager does not.

Code:
https://pastebin.com/E5EYbpEe

I hope someone can help.

**Comment by orestbida** [comment]
@RedstonePfalz, please be more specific. What exactly is the issue?

Both cookieconsent and the iframe are loaded properly on my end.

The only "issue" I see is that iframemanager is not connected to cookieconsent (cookieconsent is connected to iframemanager properly though).

**Comment by RedstonePfalz** [comment]
Thanks for your answer.
And how do I connect the iframemanager with the cookieconstent?

**Comment by orestbida** [comment]
There is an example in the readme: [Usage with cookieconsent](https://github.com/orestbida/iframemanager#usage-with-cookieconsent-v120).

Since you're using cookieconsent v2, you'll have to adapt the `onChange` method to something like this:

```javascript
im.run({
    onChange: ({changedServices, eventSource}) => {
        if(eventSource.type === 'click') {
            cc.accept('analytics');
        }
    }
});
```

This will accept the `analytics` category when the users clicks the "always load" btn (the grey one).

**Comment by RedstonePfalz** [comment]
Thanks,
it work's now.
Is the v3 of cookieconsent actually already official or still in beta?

**Comment by orestbida** [comment]
The latest release candidate — rc.12 — is stable, and if no bugs emerge in the next days/weeks, it will become the official release. Should you consider using v3, please read the [intro. section for pros. and cons](https://cookieconsent.orestbida.com/essential/introduction.html).
