### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by alxndr-w** [orestbida/iframemanager#34]
Hi, I'm using the latest RC of CookieConsent 3 but I can't reassemble this example https://stackblitz.com/edit/web-platform-mwccsc?file=index.js - I always get this kind of error and I can't explain myself why: 

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
    at H (iframemanager.js:6:3380)
    at Object.acceptService (iframemanager.js:6:4372)
    at onAccept ((Index):172:43)
    at W (cookieconsent.js:7:3657)
    at e.run (cookieconsent.js:7:20793)
H @ iframemanager.js:6
acceptService @ iframemanager.js:6
onAccept @ (Index):172
W @ cookieconsent.js:7
e.run @ cookieconsent.js:7
await in e.run (asynchron)
(anonym) @ (Index):127
```

**Comment by orestbida** [comment]
Hi @alxndr-w, what do you mean exactly with "reassemble" ?

Please provide a minimal demo with the issue.

**Comment by alxndr-w** [comment]
The reason for this error was the wrong order of my js code.

**Comment by alxndr-w** [comment]
The source of the problem is this scenario:

If I accept YouTube and go to a page without a YouTube video, I recieve this error:

<html>
<body>
<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(27, 27, 27); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" title="https://dbn.ropa-gmbh.host-003.gn2.hosting/assets/addons/wenns_sein_muss/iframemanager/iframemanager.js:6" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">iframemanager.js:6</span> <devtools-icon class="resource-links" title="Diese Nachricht im Web suchen" style="display: inline-block; white-space: nowrap; box-sizing: border-box; min-width: 0px; min-height: 0px; vertical-align: bottom; cursor: pointer;"><div class="icon-basic" style="width: 16px; height: 16px; display: block; -webkit-mask-image: url(&quot;devtools://devtools/bundled/Images/edge-search-info.svg&quot;); -webkit-mask-position: center center; -webkit-mask-repeat: no-repeat; -webkit-mask-size: 99%; background-color: var(--icon-color, var(--color-link));"></div></devtools-icon> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(225, 0, 0);">Uncaught (in promise) <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">TypeError: Cannot read properties of undefined (reading 'name')
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at H (<span class="devtools-link" role="link" tabindex="-1" title="https://dbn.ropa-gmbh.host-003.gn2.hosting/assets/addons/wenns_sein_muss/iframemanager/iframemanager.js:6:3384" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">iframemanager.js:6:3384</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Object.acceptService (<span class="devtools-link" role="link" tabindex="-1" title="https://dbn.ropa-gmbh.host-003.gn2.hosting/assets/addons/wenns_sein_muss/iframemanager/iframemanager.js:6:4376" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">iframemanager.js:6:4376</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at onAccept (<span class="devtools-link" role="link" tabindex="-1" title="https://dbn.ropa-gmbh.host-003.gn2.hosting/:163:43" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">(Index):163:43</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at W (<span class="devtools-link" role="link" tabindex="-1" title="https://dbn.ropa-gmbh.host-003.gn2.hosting/assets/addons/wenns_sein_muss/cookieconsent/cookieconsent.js:7:3657" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">cookieconsent.js:7:3657</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at e.run (<span class="devtools-link" role="link" tabindex="-1" title="https://dbn.ropa-gmbh.host-003.gn2.hosting/assets/addons/wenns_sein_muss/cookieconsent/cookieconsent.js:7:20793" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">cookieconsent.js:7:20793</span>)</span></span></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(27, 27, 27); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: consolas, lucida console, courier new, monospace; --source-code-font-size: 12px; --source-code-font-family: consolas, lucida console, courier new, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size)  !important;">

  | H | @ | iframemanager.js:6
-- | -- | -- | --
  | acceptService | @ | iframemanager.js:6
  | onAccept | @ | (Index):163
  | W | @ | cookieconsent.js:7
  | e.run | @ | cookieconsent.js:7
  | await in e.run (asynchron) |   |  
  | (anonym) | @ | (Index):123

</span></div>
</body>
</html>

Also, your demo https://stackblitz.com/edit/web-platform-ahqgz3?file=index.html has the same problem if you remove the youtube divs.

**Comment by orestbida** [comment]
Yup, can confirm it's a bug!
