### ISSUE TITLE
Parameters defined in the configuration are also added to the iframe as an attribute

### ISSUE THREAD

**Issue by MoritzLost** [orestbida/iframemanager#42]
When setting parameters using the `iframe` configuration, those params are added to the embed URL, but the `<iframe>` _also_ gets an `param` attribute with the specified string:

```js
vimeo: {
    embedUrl: 'https://player.vimeo.com/video/{data-id}',
    iframe: {
        allow: 'fullscreen; picture-in-picture, allowfullscreen',
        params: 'title=0&byline=0&portrait=0',
    },
},
```

Results in this HTML:

```html
<iframe allow="fullscreen; picture-in-picture, allowfullscreen" params="title=0&byline=0&portrait=0" lazy="" title="Vimeo" src="https://player.vimeo.com/video/252417024?title=0&byline=0&portrait=0"></iframe>
```

The `params` attribute should not be there.

Some ideas how to solve this:

- Is the `params` configuration even required? The parameters can just be added to the `embedUrl`.
- The `params` configuration value should be handled specially and not added as an attribute.
- More generically, maybe it makes sense to split the iframe _configuration_ and _attributes_ into separate configs?

**Comment by orestbida** [comment]
All properties inside the `iframe` object — except `params` and `onload` — are converted to attributes for the `iframe` element.

Initially there were only 2-3 allowed properties inside the `iframe` object (and they were not treated as iframe attributes). This was changed in later releases by allowing any property to be added to the `iframe` element as an attribute.

Yes, the special `iframe.params` prop. is/was not needed at all! I will very likely remove it whenever v2 is out!

**Comment by orestbida** [comment]
There's an array of "not allowed props" internally:
https://github.com/orestbida/iframemanager/blob/62e7a1c104ccc06b84798ec14dbd13fed2c8e8d4/src/iframemanager.js#L128C23-L128C23

Adding the `params` string to the array should do the job for now.

**Comment by MoritzLost** [comment]
> Yes, the special iframe.params prop. is/was not needed at all! I will very likely remove it whenever v2 is out!

Sounds good!

> Adding the params string to the array should do the job for now.

Agreed, this would be a good workaround until v2 is ready.
