### ISSUE TITLE
Use {data-id} on notice

### ISSUE THREAD

**Issue by joaomfantunes** [orestbida/iframemanager#46]
In one use case, it was necessary to pass the {data-id} variable within the printed message, and this variable was not rewritten by the token.
After analyzing the code, this update was possible by changing one line of code (line 568) to this:
`notice && notice_text.insertAdjacentHTML('beforeend', noticeText.replaceAll(DATA_ID_PLACEHOLDER, serviceProp._id) || '');`
Right now the code is working.

**Comment by Nantiee** [comment]
I need the same feature actually.
It would be very useful !

**Comment by orestbida** [comment]
Can be done!

**Comment by streiten** [comment]
> Can be done!

will it be done ;-) ?

**Comment by orestbida** [comment]
@streiten yep ;)
