### ISSUE TITLE
Twitter/X "Read More" not clickable

### ISSUE THREAD

**Issue by wupg98** [orestbida/iframemanager#47]
Apparently Tweets or other name "posts" on X get either rendered as images now or theres a bug
with the links now: Clicking "Read more on X" has no effect.
But last time I checked this and it worked X was still called Twitter.
So not sure if it is the iframemanager or on Xs site thats causing the issue.

**Comment by orestbida** [comment]
@wupg98 I'm not sure what you mean,  they work fine on my end.
