### ISSUE TITLE
Ist there a way to re-run?

### ISSUE THREAD

**Issue by mountbatt** [orestbida/iframemanager#48]
Hi, 

i am loading some video portfolios via ajax on an wordpress theme. Is there a way to re-run the script to detect the <divs> that are new to the dom?

Thanks for your help!

Cheers
Tobias

**Comment by eistruhe** [comment]
+1 on this. Facing the exact same issue. Running a combination of 
```js
cc.reset();
cc.run(cookieConsentConfig);
manager.run(managerConfig);
```
on each dynamic page load works, but only if the user clicks the "Load once" button. Clicking "Don't ask again" breaks the script. This probably also has to do with the CookieConsent `reset()` [function](https://cookieconsent.orestbida.com/reference/api-reference.html#reset) not being able to detect already executed scripts.

**Comment by icetee** [comment]
I create the hotfix this issue. When a page change occurs in react / next.js, it does not detect DOM changed. My solution reset and re-run iframemanager at each page change. PR #55

```js
import { useRouter } from 'next/router'
...

useEffect(() => {
  // const cc = initCookieConsent()
  const im = iframemanager()
 
  setTimeout(() => {
      im.run(...)
  }, 1000) // Since it is not SSR, it is necessary to allow time for the client to render it

  return () => {
    im.reset() // stop observers, reset scoped variables
  }
}, [router.asPath])
...
```

**Comment by orestbida** [comment]
You can now reset and re-run the plugin in v1.3.0:
```js
im.run(config);

// dom is modified ...

im.reset(true); //hard reset
im.run(config)
```
