### ISSUE TITLE
Help for using with Docusaurus

### ISSUE THREAD

**Issue by jtraulle** [orestbida/iframemanager#5]
Hello,

Thanks for this neat proposition !

I am trying to get this working with Docusaurus.

While I get it working when I load the page where the iframe is embedded (for example https://opencomp.github.io/docv2/saisir-les-resultats/utiliser-opencomp-genie/detecter-les-resultats/#en-savoir-plus-sur-les-diff%C3%A9rents-statuts-de-traitement-possibles), if  I load another page then browse to a page where the div element is inserted, the javascript is not triggered. This is due to the Single Page Application architecture used by Docusaurus v2 / react but I have no idea how to get this working on page change ?

Any idea / guidance to get this working ?

Thanks :slightly\_smiling\_face:

**Comment by orestbida** [comment]
Hi @jtraulle,

I've never used Docusaurus but - based on it's doc. - you can import any React component inside mdx files.
1. create a basic component `IframeManagerComponent` and initialize the plugin inside the `useEffect` hook:

    ```javascript
    import React, {useEffect} from 'react';
    
    import "./iframemanager.css";
    import "./iframemanager.js";
    
    export default function IframeManagerComponent() {
    
        useEffect(() => {
    
            // obtain plugin only once (important)
            if(!window._manager)
                window._manager = window.iframemanager();   
    
            window._manager.run({
                // your config
            });
    
        }, []);
    
        return (null);
    }
    ```

2. import the component in any `.mdx` file:

    ```mdx
    ---
    title: demo post
    slug: mdx-blog-post
    ---
    <!-- import component -->
    import IframeManagerComponent from "../src/components/IframeManagerComponent.js";
    
    <h1>This is title</h1>
    <p>this is description</p>
    
    <div 
        data-service="youtube" 
        data-id="861gfPVmgdc"
        data-params="start=21&mute=1"
        data-thumbnail="https://i.pinimg.com/originals/0a/4d/cb/0a4dcb92fa2d3c601b58d72720d6bec4.jpg"
        data-thumbnailpreload
        data-autoscale >
    </div>
    
    <!-- run component -->
    <IframeManagerComponent/>
    ```

**Comment by jtraulle** [comment]
Thank you for your help @orestbida, really appreciated :sunglasses: !

This is working great :tada:
