### ISSUE TITLE
dialogue and iframe created twice

### ISSUE THREAD

**Issue by alxndr-w** [orestbida/iframemanager#57]
I don't know why, but the dialogue (`<div class="cll">...</div`) on my website is created twice. It's 2x within the DOM even it's called just once:

![image](https://github.com/orestbida/iframemanager/assets/3855487/2ce3c79c-18a3-43ae-80c5-4ede01af4e51)

This is how iframemanager is called: https://github.com/alexplusde/wenns_sein_muss/blob/fe5c6cd05fa547649ed234dae9eaac10af8017e0/fragments/wsm.js.php#L4-L25

It doesn't happen in the demo though.

**Comment by orestbida** [comment]
This actually occurs when you run the plugin twice. 

If you executed it n times, you'd get n nested notices, each on top of each other.

**Comment by orestbida** [comment]
Should be fixed in 1.3.0!

Feel free to re-open the issue if that's not the case.

**Comment by AWqxKAWERbXo** [comment]
Nice! Thank you.
