### ISSUE TITLE
Firefox and firefox-like Browsers not displaying the "Twitter" iframe

### ISSUE THREAD

**Issue by wupg98** [orestbida/iframemanager#60]
I have the feeling the embedding Script for Twitter is not working on Firefox and Firefox-like Browsers. 
Can anybody replicate?
BR

**Comment by orestbida** [comment]
Please provide a full example.

**Comment by AWqxKAWERbXo** [comment]
Maybe duplicate of #10

**Comment by wupg98** [comment]
Sure!
I wasnt aware I can answer directly via mail:
When loading this page here: https://preview.tinyurl.com/2prh7sxc and
clicking accept or accept once
it stays black.
Here is the source it loads from:
https://wupg98.github.io/bhblog-iframemanager/
And here the current repository being used/loaded
https://github.com/wupg98/bhblog-iframemanager/tree/main/cookie-twitt
Best regards

Am Sa., 12. Okt. 2024 um 04:49 Uhr schrieb stale[bot] <
***@***.***>:

**Comment by orestbida** [comment]
@wupg98 there must be something wrong with your config.

I set up a [demo on Stackblitz](https://stackblitz.com/edit/stackblitz-starters-bikxwf?description=HTML/CSS/JS%20Starter&file=app.js&terminalHeight=10&title=Static%20Starter) and it works on firefox. Make sure you view the full page version.

There is however an issue related to the twitter sdk, which causes in firefox a long delay before the iframe is created.

**Comment by wupg98** [comment]
Ok thank you!
I will check it out!
Best regards

Am Sa., 12. Okt. 2024 um 10:11 Uhr schrieb Orest Bida <
***@***.***>:
